version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
      gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  init:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput || true"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure

  # ... qolgan servislar (db, redis, celery) o'zgarishsiz qoladi

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A app beat -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: